name: build-test
on:
  push:
    branches:
      - "main"
      - "dev"
      - "release-**"
  pull_request:
    branches:
      - "main"
      - "dev"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          check-latest: true
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...